version: "3.9"
services:
  ganache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8545:8545
  
  blockscanner:
    image: alethio/ethereum-lite-explorer
    ports: 
      - 80:80
    environment:
      - APP_NODE_URL=http://localhost:8545